
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package jefemayoneso.compi1prac1.Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OPEN_PARENTHESIS = 13;
  public static final int GRAPH_BAR = 16;
  public static final int NUM_INT = 32;
  public static final int TYPE_ATTR = 22;
  public static final int TYPE_PERC_ATTR = 28;
  public static final int EXTRA_ATTR = 26;
  public static final int LABEL_ATTR = 23;
  public static final int TYPE_CUANT_ATTR = 27;
  public static final int OPEN_BRACES = 5;
  public static final int DIVISION = 12;
  public static final int ERROR = 29;
  public static final int CLOSE_BRACKETS = 8;
  public static final int SEMI_COLON = 4;
  public static final int COLON = 3;
  public static final int ID = 34;
  public static final int TOTAL_ATTR = 25;
  public static final int MERGE_ATTR = 19;
  public static final int COMMA = 2;
  public static final int VALUES_ATTR = 24;
  public static final int OPEN_BRACKETS = 7;
  public static final int EOF = 0;
  public static final int NUM_DEC = 33;
  public static final int CLOSE_BRACES = 6;
  public static final int MULTIPLICATION = 11;
  public static final int DEF = 15;
  public static final int X_AXIS_ATTR = 20;
  public static final int EXECUTE_ACT = 30;
  public static final int error = 1;
  public static final int SUBSTRACTION = 10;
  public static final int GRAPH_PIE = 17;
  public static final int Y_AXIS_ATTR = 21;
  public static final int TITLE_ATTR = 18;
  public static final int ADDITION = 9;
  public static final int CLOSE_PARENTHESIS = 14;
  public static final int VAL_ON_COMILLAS = 31;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "COMMA",
  "COLON",
  "SEMI_COLON",
  "OPEN_BRACES",
  "CLOSE_BRACES",
  "OPEN_BRACKETS",
  "CLOSE_BRACKETS",
  "ADDITION",
  "SUBSTRACTION",
  "MULTIPLICATION",
  "DIVISION",
  "OPEN_PARENTHESIS",
  "CLOSE_PARENTHESIS",
  "DEF",
  "GRAPH_BAR",
  "GRAPH_PIE",
  "TITLE_ATTR",
  "MERGE_ATTR",
  "X_AXIS_ATTR",
  "Y_AXIS_ATTR",
  "TYPE_ATTR",
  "LABEL_ATTR",
  "VALUES_ATTR",
  "TOTAL_ATTR",
  "EXTRA_ATTR",
  "TYPE_CUANT_ATTR",
  "TYPE_PERC_ATTR",
  "ERROR",
  "EXECUTE_ACT",
  "VAL_ON_COMILLAS",
  "NUM_INT",
  "NUM_DEC",
  "ID"
  };
}

